### ISSUE TITLE
ArgumentError:   wrong number of arguments (given 1, expected 0)

### ISSUE THREAD

**Issue by beanieboi** [DatabaseCleaner/database_cleaner-sequel#17]
Hi,

I was following the `README` and can't get the truncation strategy to work. 
my code:

`DatabaseCleaner[:sequel].strategy = :truncation, { only: ["users"] }` (taken directly from the `README`) raises 
```
ArgumentError:
  wrong number of arguments (given 1, expected 0)
```

which I could trace down to this line:
https://github.com/DatabaseCleaner/database_cleaner/blob/master/lib/database_cleaner/cleaner.rb#L85

from my pry session inside `def create_strategy(*args)`

```
[1] pry(#<DatabaseCleaner::Cleaner>)> args
=> [:truncation, {:only=>["users"]}]
[2] pry(#<DatabaseCleaner::Cleaner>)> strategy
=> :truncation
[3] pry(#<DatabaseCleaner::Cleaner>)> strategy_args
=> [{:only=>["users"]}]
[4] pry(#<DatabaseCleaner::Cleaner>)> orm_strategy(strategy)
=> DatabaseCleaner::Sequel::Truncation
[5] pry(#<DatabaseCleaner::Cleaner>)> orm_strategy(strategy).new(*strategy_args)
ArgumentError: wrong number of arguments (given 1, expected 0)
from /Users/bfritsch/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/database_cleaner-sequel-2.0.0/lib/database_cleaner/sequel/truncation.rb:6:in `initialize'
```

Could you help me how to configure the truncation strategy?

**Comment by botandrose** [comment]
Hi Beanieboi!

The issue here is subtle, and is actually a breaking change from Ruby 2 to Ruby 3. https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/

The TL;DR is to remove the curly braces from the line.

**Comment by botandrose** [comment]
I just noticed that the curly braces are in the example code for the README for the various adapters, so I've just updated them. It may be nice to have a more helpful error message, too.

**Comment by tsuyoshi-fukuzawa** [comment]
I got similar errors. I have secondary mysql database named `:secondary` in database.yml.
When I set
```
DatabaseCleaner[:active_record, { connection: :secondary }].strategy = :transaction
result: wrong number of arguments (given 2, expected 1)
```
Then I removed the curly braces but I got
```
DatabaseCleaner[:active_record, connection: :secondary].strategy = :transaction
result: unknown keyword: :connection
```

rails: 6.1.3.1
database_cleaner (2.0.1)
ruby: 3.0.1p64
