### ISSUE TITLE
Release v2.0.1

### ISSUE THREAD

**Issue by etagwerker** [DatabaseCleaner/database_cleaner-sequel#24]
Hey @botandrose, 

I wanted to push v2.0.1 but it seems that I don't have permissions for this. 

It would be great if you gave me access to the gem in RubyGems or pushed v2.0.1 yourself.

Either way, submitting this so that I don't forget. 😄 

Thanks!

**Comment by botandrose** [comment]
@etagwerker Oh! Just granted you access to the entire family of database_cleaner gems

**Comment by etagwerker** [comment]
@botandrose Thank you! I just released v2.0.1
